<?php

/**
 * BaseVentaEquipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $fecha
 * @property string $tipo
 * @property integer $monto
 * @property string $detalle
 * @property Doctrine_Collection $equipos
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method timestamp           getFecha()   Returns the current record's "fecha" value
 * @method string              getTipo()    Returns the current record's "tipo" value
 * @method integer             getMonto()   Returns the current record's "monto" value
 * @method string              getDetalle() Returns the current record's "detalle" value
 * @method Doctrine_Collection getEquipos() Returns the current record's "equipos" collection
 * @method VentaEquipo         setId()      Sets the current record's "id" value
 * @method VentaEquipo         setFecha()   Sets the current record's "fecha" value
 * @method VentaEquipo         setTipo()    Sets the current record's "tipo" value
 * @method VentaEquipo         setMonto()   Sets the current record's "monto" value
 * @method VentaEquipo         setDetalle() Sets the current record's "detalle" value
 * @method VentaEquipo         setEquipos() Sets the current record's "equipos" collection
 * 
 * @package    tesis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVentaEquipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('venta_equipo');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('tipo', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('monto', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('detalle', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Equipo as equipos', array(
             'local' => 'id',
             'foreign' => 'venta_equipo_id'));
    }
}