<?php

/**
 * BaseEmpleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $rut
 * @property string $nombres
 * @property string $apellidos
 * @property string $email
 * @property timestamp $fecha_nac
 * @property string $direccion
 * @property string $ciudad_residencia
 * @property integer $telefono
 * @property timestamp $fecha_contrato
 * @property timestamp $fecha_fin_contrato
 * @property integer $sueldo
 * @property integer $nombre_usuario
 * 
 * @method integer   getId()                 Returns the current record's "id" value
 * @method string    getRut()                Returns the current record's "rut" value
 * @method string    getNombres()            Returns the current record's "nombres" value
 * @method string    getApellidos()          Returns the current record's "apellidos" value
 * @method string    getEmail()              Returns the current record's "email" value
 * @method timestamp getFechaNac()           Returns the current record's "fecha_nac" value
 * @method string    getDireccion()          Returns the current record's "direccion" value
 * @method string    getCiudadResidencia()   Returns the current record's "ciudad_residencia" value
 * @method integer   getTelefono()           Returns the current record's "telefono" value
 * @method timestamp getFechaContrato()      Returns the current record's "fecha_contrato" value
 * @method timestamp getFechaFinContrato()   Returns the current record's "fecha_fin_contrato" value
 * @method integer   getSueldo()             Returns the current record's "sueldo" value
 * @method integer   getNombreUsuario()      Returns the current record's "nombre_usuario" value
 * @method Empleado  setId()                 Sets the current record's "id" value
 * @method Empleado  setRut()                Sets the current record's "rut" value
 * @method Empleado  setNombres()            Sets the current record's "nombres" value
 * @method Empleado  setApellidos()          Sets the current record's "apellidos" value
 * @method Empleado  setEmail()              Sets the current record's "email" value
 * @method Empleado  setFechaNac()           Sets the current record's "fecha_nac" value
 * @method Empleado  setDireccion()          Sets the current record's "direccion" value
 * @method Empleado  setCiudadResidencia()   Sets the current record's "ciudad_residencia" value
 * @method Empleado  setTelefono()           Sets the current record's "telefono" value
 * @method Empleado  setFechaContrato()      Sets the current record's "fecha_contrato" value
 * @method Empleado  setFechaFinContrato()   Sets the current record's "fecha_fin_contrato" value
 * @method Empleado  setSueldo()             Sets the current record's "sueldo" value
 * @method Empleado  setNombreUsuario()      Sets the current record's "nombre_usuario" value
 * 
 * @package    tesis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpleado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empleado');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('rut', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('nombres', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('apellidos', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('email', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 45,
             ));
        $this->hasColumn('fecha_nac', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('direccion', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('ciudad_residencia', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('telefono', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('fecha_contrato', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_fin_contrato', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('sueldo', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('nombre_usuario', 'integer', 45, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}