<?php

/**
 * BaseCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_categoria
 * @property string $descripcion
 * @property string $tipo
 * 
 * @method integer   getId()               Returns the current record's "id" value
 * @method string    getNombreCategoria()  Returns the current record's "nombre_categoria" value
 * @method string    getDescripcion()      Returns the current record's "descripcion" value
 * @method string    getTipo()             Returns the current record's "tipo" value
 * @method Categoria setId()               Sets the current record's "id" value
 * @method Categoria setNombreCategoria()  Sets the current record's "nombre_categoria" value
 * @method Categoria setDescripcion()      Sets the current record's "descripcion" value
 * @method Categoria setTipo()             Sets the current record's "tipo" value
 * 
 * @package    tesis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('nombre_categoria', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('descripcion', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('tipo', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}