<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/16 21:19:46
sfConfig::add(array(
  'mod_administrarcategorias_enabled' => true,
  'mod_administrarcategorias_view_class' => 'sfPHP',
));
