<?php

/**
 * ContainerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContainerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContainerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Container');
    }
}