<?php

/**
 * EquipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Equipo');
    }
}