<?php

/**
 * VentaChatarraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VentaChatarraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VentaChatarraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VentaChatarra');
    }
}