<?php

/**
 * BaseVentaChatarra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $monto
 * @property timestamp $fecha
 * @property string $detalle
 * @property string $tipo
 * @property integer $cliente_id
 * @property Doctrine_Collection $Containers
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getMonto()      Returns the current record's "monto" value
 * @method timestamp           getFecha()      Returns the current record's "fecha" value
 * @method string              getDetalle()    Returns the current record's "detalle" value
 * @method string              getTipo()       Returns the current record's "tipo" value
 * @method integer             getClienteId()  Returns the current record's "cliente_id" value
 * @method Doctrine_Collection getContainers() Returns the current record's "Containers" collection
 * @method VentaChatarra       setId()         Sets the current record's "id" value
 * @method VentaChatarra       setMonto()      Sets the current record's "monto" value
 * @method VentaChatarra       setFecha()      Sets the current record's "fecha" value
 * @method VentaChatarra       setDetalle()    Sets the current record's "detalle" value
 * @method VentaChatarra       setTipo()       Sets the current record's "tipo" value
 * @method VentaChatarra       setClienteId()  Sets the current record's "cliente_id" value
 * @method VentaChatarra       setContainers() Sets the current record's "Containers" collection
 * 
 * @package    tesis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVentaChatarra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('venta_chatarra');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('monto', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('detalle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('cliente_id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Container as Containers', array(
             'local' => 'id',
             'foreign' => 'venta_chatarra_id'));
    }
}