<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/15 09:30:22
sfConfig::add(array(
  'mod_administrarempleados_enabled' => true,
  'mod_administrarempleados_view_class' => 'sfPHP',
));
