<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/14 06:19:06
sfConfig::add(array(
  'mod_administrarequipos_enabled' => true,
  'mod_administrarequipos_view_class' => 'sfPHP',
));
