<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/15 09:30:26
sfConfig::add(array(
  'mod_administrarcontenedor_enabled' => true,
  'mod_administrarcontenedor_view_class' => 'sfPHP',
));
