<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/15 11:12:19
sfConfig::add(array(
  'mod_administrarventachatarra_enabled' => true,
  'mod_administrarventachatarra_view_class' => 'sfPHP',
));
