<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/15 11:10:25
sfConfig::add(array(
  'mod_administrarventapieza_enabled' => true,
  'mod_administrarventapieza_view_class' => 'sfPHP',
));
