<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/15 11:32:04
sfConfig::add(array(
  'mod_administrarpiezas_enabled' => true,
  'mod_administrarpiezas_view_class' => 'sfPHP',
));
