<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/15 09:30:33
sfConfig::add(array(
  'mod_administrarusuarios_enabled' => true,
  'mod_administrarusuarios_view_class' => 'sfPHP',
));
