<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/15 09:30:36
sfConfig::add(array(
  'mod_administrarequipos_enabled' => true,
  'mod_administrarequipos_view_class' => 'sfPHP',
));
