<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/15 11:20:50
sfConfig::add(array(
  'mod_administrarventaequipo_enabled' => true,
  'mod_administrarventaequipo_view_class' => 'sfPHP',
));
