<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/15 11:12:31
sfConfig::add(array(
  'mod_administrarclientes_enabled' => true,
  'mod_administrarclientes_view_class' => 'sfPHP',
));
