<?php

/**
 * PiezaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PiezaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PiezaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pieza');
    }
}