<?php

/**
 * VentaPiezaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VentaPiezaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VentaPiezaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VentaPieza');
    }
}