<?php

/**
 * VentaEquipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VentaEquipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VentaEquipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VentaEquipo');
    }
}